/**
 * Zipf lookup backed by {lang}_word_zipf.json (generated by export_zipf.py).
 */

import fs from "fs";
import path from "path";
import { spawnSync } from "child_process";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const cache = new Map();

export function loadZipfDict(lang = "es") {
  if (cache.has(lang)) return cache.get(lang);

  const jsonPath = path.join(__dirname, `${lang}_word_zipf.json`);
  if (!fs.existsSync(jsonPath)) {
    const script = path.join(__dirname, "export_zipf.py");
    const result = spawnSync("python", [script, "--lang", lang], { stdio: "inherit" });
    if (result.status !== 0) {
      throw new Error(`Failed to generate ${lang}_word_zipf.json — run: python export_zipf.py --lang ${lang}`);
    }
  }

  const dict = new Map(Object.entries(JSON.parse(fs.readFileSync(jsonPath, "utf8"))));
  cache.set(lang, dict);
  return dict;
}

export function zipfFrequency(word, lang = "es") {
  const lower = word.toLowerCase();
  const table = loadZipfDict(lang);
  return table.has(lower) ? table.get(lower) : 0;
}

export function readLangFromFile(filePath) {
  const head = fs.readFileSync(filePath, { encoding: "utf8", flag: "r" }).slice(0, 32);
  const match = head.match(/^# lang=([a-z]{2})/);
  return match ? match[1] : "es";
}
